### ISSUE TITLE
Rename default export from 'sqltag' to 'sql'

### ISSUE THREAD

**Issue by TobiasWalle** [blakeembrey/sql-template-tag#14]
[Intellij](https://www.jetbrains.com/idea/)s auto import feature uses the variable name of the default export for the suggestions. So if I type `sql`, Intellij actually recommends `sqltag` (screenshot). So I need to rename the import manually.

![image](https://user-images.githubusercontent.com/9933601/91568846-e9a2d780-e945-11ea-9a60-6d31ce1a980b.png)

Would it be possible to rename the exported variable from `sqltag` to `sql`? This would resolve my issue.

I could also open a PR for this.

**Comment by blakeembrey** [comment]
I’m fairly indifferent but not eager to release a breaking change. Does IntelliJ support the default export? That was intended so you didn’t need to use the name defined by this library. If you want to submit a backward compatible PR I can accept it too.

**Comment by TobiasWalle** [comment]
@blakeembrey I just mean the default export. So this wouldn't be a breaking change.
It could be implemented like the following:
```javascript
const sql = sqltag;
export default sql;
```
