### ISSUE TITLE
Enable Wiki

### ISSUE THREAD

**Issue by ivan-kleshnin** [blakeembrey/sql-template-tag#16]
Hi, Blake! Thank you for making this library 👍 
Plain SQL is such a joy to work with, unlike ORMs :)

I'm using this tool and I'd like to share some code I made.
Some cookbook-style stuff which can be copy-pasted and used by others.

Such things are commonly placed in Wikis but

https://github.com/blakeembrey/sql-template-tag/wiki 
redirects to
https://github.com/blakeembrey/sql-template-tag

**Comment by blakeembrey** [comment]
By default wikis are limited to collaborators, did you want to send a PR for documentation instead? I can also add you as collaborator if you’d like for wikis, but I don’t want to have it open to the public in case it starts to get spammed.

**Comment by ivan-kleshnin** [comment]
Ah, ok. I initially thought that spamming the docs with some 3rd party opinions would be a problem. 
But, if you're open to some small contributions like that – good! 

In that case I'd like to experiment a bit more with the snippets I have in mind.
I belive, quality requirements to READMEs are higher than Wikis so I'd like to give it some time.
If you're fine with open issue – let it hang like this for about a week. If not – feel free to close and I'll make a separate PR.
Different projects have very different issue policies, you know.

**Comment by blakeembrey** [comment]
I'm going to close this out and have enabled discussions for any future thoughts on this! 😄
