### ISSUE TITLE
Can't even SHOW_TABLES;

### ISSUE THREAD

**Issue by jedmao** [blakeembrey/sql-template-tag#2]
First off, ❤️  the first-class TS support 😄 

## Before

```ts
mysql.query('SHOW TABLES')
```

Everything is fine 👍 

## After

```ts
mysql.query(sql`SHOW TABLES`)
```

👎 

> ER_EMPTY_QUERY: Query was empty

---

1. Any idea why this might be the case?
1. What is the proper way to debug this?

**Comment by blakeembrey** [comment]
Taking a look. Based on the documentation (https://github.com/mysqljs/mysql#performing-queries) this should _just work_.

**Comment by blakeembrey** [comment]
Just to clarify, are you using the MySQL module above?

**Comment by blakeembrey** [comment]
Ok, I think I see the issue. It relates to: https://github.com/mysqljs/mysql/blob/master/lib/Connection.js#L39-L41.

The `sql` and `values` properties aren't actually enumerable. This isn't an issue with `pg`, I'll see if there's an easy way to change this here or in MySQL, but `get` and `set` is by default not enumerable in JS.

**Comment by blakeembrey** [comment]
Went ahead and just fixed it here by making the keys enumerable: https://github.com/blakeembrey/sql-template-tag/pull/5.

**Comment by jedmao** [comment]
Thanks!
