### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by quolpr** [blakeembrey/sql-template-tag#25]
Hi! Thank you for the awesome library! Could you add the browser support? I am using absurd-sql, and I need the basic SQL builder. At now `import { inspect } from "util";` doesn't allow me to use in browser(I am using vite)

**Comment by blakeembrey** [comment]
Thanks for the flag, it should be possible to switch this over to symbols and/or remove the feature entirely.

**Comment by blakeembrey** [comment]
Fixed in https://github.com/blakeembrey/sql-template-tag/releases/tag/v4.1.0

I'll release a v5 later today with ES support and drop some extra cruft from the module, so either 4.1 or 5.0 will work for you.

**Comment by quolpr** [comment]
Wow, thank you so much for the fast fix!
