### ISSUE TITLE
Support of the dedupe?

### ISSUE THREAD

**Issue by quolpr** [blakeembrey/sql-template-tag#27]
Is there any chance that dedupe will be supported, like in https://github.com/XeCycle/pg-template-tag/issues/5#issuecomment-386875336 ?

**Comment by blakeembrey** [comment]
Probably not, I decided the complexity and performance overhead for extremely marginal gains wouldn't be worth it.

**Comment by blakeembrey** [comment]
Could certainly be convinced I'm wrong, there's a small benchmarking script that can be used for any code tweaks to check performance. Do you have a use-case where you expect a meaningful amount of duplication?
