### ISSUE TITLE
Feature: joinSql()

### ISSUE THREAD

**Issue by mindplay-dk** [blakeembrey/sql-template-tag#29]
I'm creating a simple query-builder based on this package.

While `join` works for joining lists of *values*, I needed a way to join a list of *query fragments*.

I came up with this:

```ts
import { Sql, empty } from "sql-template-tag";

export function joinSql(sqls: Array<Sql>, separator: string): Sql {
  return sqls.length > 0
    ? new Sql(["", ...new Array(sqls.length - 1).fill(separator), ""], sqls)
    : empty;
}
```

This can be used, for example, to join `Sql` instances with `WHERE` clauses in them, e.g.:

```ts
const terms = [
  sql`user.first_name LIKE ${first_name}`,
  sql`user.last_name LIKE ${last_name}`,
];

const query = sql`SELECT * FROM user WHERE ${joinSql(terms, " AND ")}`;
```

It can also be used to join lists of relations:

```ts
const relations = [
  sql`user.first_name`,
  sql`${new Date()} - user.date_of_birth AS age`,
];

const query = sql`SELECT ${joinSql(relations, ", ")} FROM user`;
```

<details>
<summary>I have some tests in my project with a more precise spec. (click to expand.)</summary>

(This isn't Jest, but should be easy to port.)

```ts
import { test } from "../test/harness.js";
import { joinSql, sql } from "./sql.js";

test(`can join query fragments`, async is => {
  const first_name = "Rasmus";
  const last_name = "Schultz";

  const two_terms = joinSql([
    sql`user.first_name = ${first_name}`,
    sql`user.last_name = ${last_name}`,
  ], " AND ");

  is.equal(
    two_terms.sql,
    `user.first_name = ? AND user.last_name = ?`,
    `it joins the terms`
  );

  is.equal(
    two_terms.values,
    [first_name, last_name],
    `it joins the values`
  );

  const single_term = joinSql([
    sql`user.first_name = ${first_name}`,
  ], " AND ");

  is.equal(
    single_term.sql,
    `user.first_name = ?`,
    `when there is only one term, the separator goes unused`
  );

  is.equal(
    single_term.values,
    [first_name],
    `it copies the value`
  );

  const zero_terms = joinSql([], " AND ");

  is.equal(zero_terms.sql, ``, `empty SQL when no terms given`);

  is.equal(zero_terms.values, [], `empty values when no terms given`);
});
```

</details>

It seems to nicely compliment `join` and has quite a few interesting use cases in my project already - it's quite a simple addition and very versatile, whether you're hand-building query-builders or a generic query-abstraction.

I was wondering if you would consider this for the library? 🙂

**Comment by blakeembrey** [comment]
I love it, but I actually this `join` can already do this for you. We don't need a separate function. The only difference between your example and the [one in the library](https://github.com/blakeembrey/sql-template-tag/blob/fd2f34be8db4ccacc14d52a9d404ce0e2f72d87f/src/index.ts#L98-L106) is defaulting to `empty`, but I still think that's a bad idea because your `WHERE` becomes invalid SQL - best to handle that properly.

**Comment by blakeembrey** [comment]
Just added the examples you provided to the test suite to confirm it's supported. Let me know if there's something missing though!

**Comment by mindplay-dk** [comment]
Oh, my implementation of `joinSql` is literally identical to `join`, ha. 😅

I just assumed that wouldn't work, because of the documentation:

> Create a SQL query **for a list of values**.

And the examples show this being used to join lists of values.

Well, good to have this covered by tests either way, but probably the documentation should cover this?

**Comment by blakeembrey** [comment]
How does https://github.com/blakeembrey/sql-template-tag/commit/9c9afe7824825ae1f978aa99a7bcf9d0af769635 look to you?
