### ISSUE TITLE
join([]) causes "Expected 2 strings to have 1 values"

### ISSUE THREAD

**Issue by taylorgoolsby** [blakeembrey/sql-template-tag#3]
An example: https://runkit.com/croolsby/sql-template-tag-join-issue

If you run `join()` on an empty array, I.E. `join([])`, it returns an error "Expected 2 strings to have 1 values".

I think it's correct for `join([])` to throw an error because it's not clear what value `join([])` should return. If `join([])` returns and empty string or `null`, that would cause an error in SQL syntax, usually.

However, I think the error message is unhelpful for debugging. Can we change the error message to something more helpful for this special case: `join([])`?

**Comment by blakeembrey** [comment]
I'm not 100% convinced this should be an error, if only because plain JavaScript isn't, e.g. `[].join()`. I'd be inclined to follow the standard language behavior first. Do you have strong feelings against this?

**Comment by taylorgoolsby** [comment]
That's a good point. 

Personally, I would like it to throw an error because it's never my intention that `join([])` returns the empty string. I think the most common use cases for `join([])` is in WHERE IN and INSERT VALUES statements, for example:

```
const sql = sqltag`
  SELECT * FROM User WHERE IN (${join([])});
`

const users = [{name: 'Alice'}, {name: 'Bob'}]
const values = users.map(u => sqltag`(${u.name})`)
const sql = sqltag`
  INSERT INTO User (
    name
  ) VALUES ${join(values)};
`
```

Using the examples above, if `join([])` were to return the empty string, then we would get:

```
SELECT * FROM User WHERE IN ('');

INSERT INTO User (name) VALUES '';
```

The INSERT statement will throw an error if it's executed, however, what I'm worried about is the WHERE IN case. This will not throw any error and unexpected behavior will happen.

In either case, I can't see why anyone would want `join([])` to return the empty string.

**Comment by taylorgoolsby** [comment]
BTW, in normal javascript, the examples above would actually be:

```
SELECT * FROM User WHERE IN ();

INSERT INTO User (name) VALUES ;
```

This is because
```
const sql = sqltag`${''}`
```
gets flattened to `"''"`, that is, a string containing `''`.

However, in normal javascript
```
const sql = `${''}`
```
gets flattened to `''`, which is the empty string.

**Comment by blakeembrey** [comment]
Just to clarify, the intention would never be for `join([])` to return an empty string, but rather empty SQL, e.g.

```
sql``
```

However, I think your argument is reason and will make this throw an error instead. I can't currently see a use-case for `join([])` working within any of my own code (it's probably a bug that'll produce a SQL syntax error later). I do have a few places where it's negligible if it does nothing though.

**Comment by blakeembrey** [comment]
In my example above the difference is that `join([''])` would produce `{ text: '$1', values: [''] }` while `join([])` would produce `{ text: '', values: [] }`. Hope that explains things a bit better, opening a PR with it being an error now though!
