### ISSUE TITLE
support for type mapping

### ISSUE THREAD

**Issue by shahinghasemi** [blakeembrey/sql-template-tag#30]
Hello, is there any plan for type mapping? This is useful especially for Prisma upgrade to v4.
The desired output is something like this:
```
    const obj = {
      text: 'insert into "ResponseLog" ("examId","participantId","questionId","value","submitTime") values($1::uuid,$2::uuid,$3::uuid,$4::json,$5::timestamp),
      sql: '...',
      values: [
        '...',
        '...',
        '...',
        '...',
        '...',
      ],
    };
```
which accepts the types as a parameter.

something like this can help:
```
types = ['uuid', 'uuid', 'timestamp'] ...
joinedValues.text.replace(/(\d+)/g, (match) => {
    const realIndex = (parseInt(match, 10) - 1) % types.length;
    return `${match}::${types[realIndex]}`;
  });
```

Thanks.

**Comment by blakeembrey** [comment]
No, there is not plan for this. You can write the types in your query.

**Comment by shahinghasemi** [comment]
> You can write the types in your query.

Would you please give me an example? The problem that I couldn't handle is, `text` is `read-only` therefore can't be modified using the above `replace` function. Is there any not-hacky solution? 

thanks in advance.

**Comment by blakeembrey** [comment]
Your initial issue doesn’t have enough information to be very helpful, but why can’t you just write:

```ts
sql`INSERT INTO … VALUES(${value}::uuid, …)`
```
