### ISSUE TITLE
Auto Join

### ISSUE THREAD

**Issue by crisward** [blakeembrey/sql-template-tag#43]
Its really common in sql to want to dump an array of integers for a `in` comparison. It'd be nice if a value was an array for it to be auto joined with commas. WDYT??

```javascript
let user_ids = [1,2,3]
sql`select * from users where id in (${user_ids})`

// select * from users where id in (?,?,?)
```

I realise you can already do this with join. But it could be nice to simplify the api for common use cases.

**Comment by blakeembrey** [comment]
It's a good idea, but unfortunately not something I want to maintain as I'd have to start parsing SQL. See https://github.com/blakeembrey/sql-template-tag/pull/32 for a similar issue/conversation. 

Also, postgres supported `WHERE (x, y) IN (...)` using tuples, and although I can't recall if the underlying `pg` engine is automatically serializing arrays for this use-case, it's a good reason to keep things flexible in case they can later.
