### ISSUE TITLE
massive memory usage

### ISSUE THREAD

**Issue by wzrdtales** [blakeembrey/sql-template-tag#7]
Love this module, but it uses a massive amount of memory. There is an exhaustive amount of calls to values and strings, which causes this.

Just leaving this note here for now.

**Comment by wzrdtales** [comment]
The memory overhead partially results from the internal handling and unnecessary copying + something related to postgres.

**Comment by wzrdtales** [comment]
ok overhead of postgres is just b/c values also gets called

**Comment by blakeembrey** [comment]
Thanks for the flag, this could be improved. I’ll look into adding some benchmarks around this to verify where the overhead lies, but it’s most likely related to the lazy generation of values and caching of the generated values. One idea would be to make it eager and avoid keeping the raw data around in memory after it’s been consumed.

**Comment by blakeembrey** [comment]
I created a branch here but am unable to replicate any memory leaks: https://github.com/blakeembrey/sql-template-tag/tree/be/reduce-overhead. In any case, I refactored the code to eagerly build strings and values which would reduce the memory overhead and allow the GC to discard references to child instances.

**Comment by wzrdtales** [comment]
I work with massive queries, so that is why I stumbled upon this. I already reworked yesterday everything myself:

https://github.com/wzrdtales/sql-template-tag/blob/47bd250d736bbd7d0caacf60aca3b6f81d6cce4a/src/index.ts

**Comment by wzrdtales** [comment]
to the pre allocation, I considered it (I had the knowledge before already that this is one of the, if not the fastest merge operation) since I noticed that the processing of my queries take  a considerable amount of time (as said I have big queries that build up gradually (Bulk inserts) and I have added it now, it is definitely worth it, 66% performance improvement. That adjusted the throughput speed once again for the app I am using it.

I will open a merge request so you can keep track of the changes of me and decide if you want to go with my version or not.

**Comment by blakeembrey** [comment]
Awesome, thanks for the contribution!

**Comment by blakeembrey** [comment]
Working off your PR I think I've managed to halve the memory usage again. Benchmark included in my latest push to `master` so feel free to run it and double check. With this work:

```
before: 67.15MB / 98.13MB
after: 462.72MB / 497.67MB
difference: 395.57MB
time: 1s 78ms
```

With changes to compute length and initialize a single array (instead of resizing the array):

```
before: 66.68MB / 99.63MB
after: 267.1MB / 311.74MB
difference: 200.42MB
time: 0s 624ms
```

**Comment by wzrdtales** [comment]
i see you think that resizing the empty array like done here https://github.com/blakeembrey/sql-template-tag/pull/8/files#diff-f41e9d04a45c83f3b6f6e630f10117feR43 will have performance impact. I just validated and it does not have a performance impact though. I guess node doesn't start allocating the memory in that case, but in theory you're correct that this should make it a little bit more performant assuming the array gets resized on every iteration.

**Comment by wzrdtales** [comment]
i did not yet check the memory part though, but time results in exactly the same in that case. but I think it is a good addition on top.

satisfied to see the changes merged in, means I can switch off my custom release for our production services again :)

**Comment by wzrdtales** [comment]
the timing result from my side:

```
Depth: 5000
Average: 1087ms

Depth: 500
Average: 7
```

With your changes

```
Depth: 5000
Average: 1070ms

Depth: 500
Average: 7
```
