### ISSUE TITLE
Missing essential information from the documentation

### ISSUE THREAD

**Issue by GrzegorzWidla** [blakeembrey/sql-template-tag#9]
Current README file contains the following paragraph:

> The main difference between this module and others is first-class TypeScript. There's also the raw, join and empty helpers. Specific differences **are documented below**

And then there is nothing below documenting `raw`, `join`, and `empty` helpers.

Proposed solutions:

1. Removed the last sentence, i.e. `Specific differences are documented below`.
2. Update documentation to include actual explanation of how they can be used.

**Comment by blakeembrey** [comment]
Feel free to submit a PR.

**Comment by geocine** [comment]
usage example does not include `raw` but was able to infer what id does by looking at the linked [sql-template-strings](https://github.com/felixfbecker/node-sql-template-strings)
